name: Docker
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plex-alpine
        uses: actions/checkout@v3
        with:
          path: plex-alpine
      - name: Checkout original linuxserver/docker-plex
        uses: actions/checkout@v3
        with:
          repository: linuxserver/docker-plex
          ref: master
          path: docker-plex
      - run: |
          cd docker-plex
          git apply ../plex-alpine/Dockerfile.patch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker-plex
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
