name: Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  scan:
    name: Check for new tag
    runs-on: ubuntu-latest
    steps:
      - name: Scan Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
#          repo-url: https://ghcr.io         
          image: linuxserver/plex
          tag-regex: "^\\d+\\.\\d+\\.\\d+$"
          max-age-minutes: 360
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
        id: scan
      - name: Print
        run: |
          echo "TAGS=${{ steps.scan.outputs.tags }}" >> $GITHUB_ENV
          echo 'Recent updates: ${{ steps.scan.outputs.tags }}'
      - if: ${{ env.TAGS }}
        name: Trigger Build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh --repo ${{ github.repository }} workflow run Docker -f TAGS='${{ env.TAGS }}'

