name: Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scan:
    name: Check for new tag
    runs-on: ubuntu-latest
    steps:
      - name: Scan Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
#          repo-url: https://ghcr.io         
          image: linuxserver/plex
          tag-regex: "^\\d+\\.\\d+\\.\\d+$"
          max-age-minutes: 15000
#          max-age-minutes: 15
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"
  build:
    needs: scan
    if: steps.scan.outputs.tags
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: "echo 'trigger build: ${{ steps.scan.outputs.tags }}'"

